package com.makstuff.minimalistcaloriecounter.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF696969)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6E6E6)
val md_theme_light_onPrimaryContainer = Color(0xFF1F1F1F)
val md_theme_light_secondary = Color(0xFF616161)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9D9D9)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1F1F)
val md_theme_light_tertiary = Color(0xFF666666)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF2F2F2)
val md_theme_light_onTertiaryContainer = Color(0xFF212121)
val md_theme_light_error = Color(0xFFBABABA)
val md_theme_light_errorContainer = Color(0xFFFFFFFF)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF404040)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1C1C1C)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1C1C)
val md_theme_light_surfaceVariant = Color(0xFFE3E3E3)
val md_theme_light_onSurfaceVariant = Color(0xFF474747)
val md_theme_light_outline = Color(0xFF787878)
val md_theme_light_inverseOnSurface = Color(0xFFF2F2F2)
val md_theme_light_inverseSurface = Color(0xFF303030)
val md_theme_light_inversePrimary = Color(0xFFD4D4D4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF696969)
val md_theme_light_outlineVariant = Color(0xFFC7C7C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD4D4D4)
val md_theme_dark_onPrimary = Color(0xFF363636)
val md_theme_dark_primaryContainer = Color(0xFF4F4F4F)
val md_theme_dark_onPrimaryContainer = Color(0xFFF0F0F0)
val md_theme_dark_secondary = Color(0xFFC9C9C9)
val md_theme_dark_onSecondary = Color(0xFF333333)
val md_theme_dark_secondaryContainer = Color(0xFF4A4A4A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8E8E8)
val md_theme_dark_tertiary = Color(0xFFD1D1D1)
val md_theme_dark_onTertiary = Color(0xFF383838)
val md_theme_dark_tertiaryContainer = Color(0xFF4F4F4F)
val md_theme_dark_onTertiaryContainer = Color(0xFFEDEDED)
val md_theme_dark_error = Color(0xFFFFFFFF)
val md_theme_dark_errorContainer = Color(0xFF949494)
val md_theme_dark_onError = Color(0xFF696969)
val md_theme_dark_onErrorContainer = Color(0xFFFFFFFF)
val md_theme_dark_background = Color(0xFF1C1C1C)
val md_theme_dark_onBackground = Color(0xFFE3E3E3)
val md_theme_dark_surface = Color(0xFF1C1C1C)
val md_theme_dark_onSurface = Color(0xFFE3E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF474747)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C7C7)
val md_theme_dark_outline = Color(0xFF919191)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C1C)
val md_theme_dark_inverseSurface = Color(0xFFE3E3E3)
val md_theme_dark_inversePrimary = Color(0xFF696969)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD4D4D4)
val md_theme_dark_outlineVariant = Color(0xFF474747)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF696969)
